### ISSUE TITLE
Question: Does the Thanos Ruler deduplicate?

### ISSUE THREAD

**Issue by dbluxo** [improbable-eng/thanos#1079]
I am learning and playing around with Thanos. I have created a quickstart for Thanos (docker-compose): https://github.com/dbluxo/quickstart-thanos

I am not sure, how to get this alarm working in my setup: https://github.com/improbable-eng/thanos/blob/master/tutorials/kubernetes-demo/manifests/thanos-ruler.yaml#L6

Thanos Querier is returning `2` without deduplication and `1` with deduplication:

![Bildschirmfoto 2019-04-25 um 08 37 37](https://user-images.githubusercontent.com/20679842/56714973-98257f80-6736-11e9-87e3-ab46308ff051.png)

Thanos Ruler is firing, because the threshold of 2 is fallen below:

![Bildschirmfoto 2019-04-25 um 08 38 31](https://user-images.githubusercontent.com/20679842/56714977-9b207000-6736-11e9-8d1d-900ceec4791d.png)

Does the Thanos Ruler deduplicate or where is my mistake?

**Comment by bwplotka** [comment]
Yes and No.

Thanos Ruler does not deduplicate, but it asks (explicitly) for deduplicated results. 

AC for this issue:
* Add this mention to https://github.com/improbable-eng/thanos/blob/master/docs/components/rule.md

**Comment by dbluxo** [comment]
Thx! But how to write an alert for Thanos Ruler to notify that one from two Prometheus replicas is down?

E.g. for cluster `seattle` with replica `r1`and `r2`:

![Bildschirmfoto 2019-04-25 um 16 34 33](https://user-images.githubusercontent.com/20679842/56744063-19e9cd00-6778-11e9-89fa-7d7cfe2b99c4.png)

**Comment by bwplotka** [comment]
This is not Ruler responsiblity, but rather Prometheus alert itself. As mentioned in docs, use Ruler only for global alerts: Alerts that requires global view OR long retention

**Comment by dbluxo** [comment]
Okay, I got it. It could be only possible if the Ruler would append (optionally) the `'dedup=false'` parameter in the request.

I was just confused why you have used `== 2` in your demo as threshold for the alert: https://github.com/improbable-eng/thanos/blob/88544fcee0d902a2118ea11891b789d97a8a571c/tutorials/kubernetes-demo/manifests/thanos-ruler.yaml#L16 and thought that it would be possible to recognize, if only one replica is down.

**Comment by bwplotka** [comment]
Wait wait wait :p I am sorry for confusion but:

> Thanos Ruler does not deduplicate, but it asks (explicitly) for deduplicated results, so your result is expected.

... All is true except the expected result (for typical setup, at least).

Essentially both up queries for Prometheus should be 2 if all is set correctly (replica labels in correct places, sane relabelling etc) This is because querier shows what Prometheus collected. And Prometheus (in my demo) collected info about 2 pods (if they are up). That's why ruler could check for number of replicas etc. But still it is adviced to have this rule in prometheus itself IMO, however ruler should be able to do it as well. 

This all assumes that you are not doing something magic with your relabelling or replica label! Can we dive into this, why dedup true with up gives 1? What is your replica label configured on querier?

> Okay, I got it. It could be only possible if the Ruler would append (optionally) the 'dedup=false' parameter in the request.

No. I think it is sane to have it hardcoded to true. Not sure what would be the use case to operate on replicated data. I think there is none.

**Comment by dbluxo** [comment]
Ahh, thank you for that hint!:

> Essentially both up queries for Prometheus should be 2 if all is set correctly (replica labels in correct places, sane relabelling etc) This is because querier shows what Prometheus collected. And Prometheus (in my demo) collected info about 2 pods (if they are up).

My `up` queries in Prometheus have shown `1` because the Prometheus instances did not query each other. I changed it, now it works! :-)
