### ISSUE TITLE
Thanos: Remote read api

### ISSUE THREAD

**Issue by accent-atul** [improbable-eng/thanos#1128]
We want to have multiple Thanos clusters for our monitoring stack, and will need query and aggregate all the clusters. We are exploring if we can upfront multiple Thanos clusters with Prometheus instance and use Thanos remote read API if available. 
Prometheus by default has /api/v1/read remote read API. Is the same available for Thanos ?

**Comment by bwplotka** [comment]
No. Thanos was designed to be end system for querying, so no federation/remote read was added. I would say for Thanos the 1:1 to `/api/v1/read` is grpc `Store.Series`.

I guess it is very straightforward to implement proxy that talks to any server exposing [Store.Series gRPC ](https://github.com/improbable-eng/thanos/blob/master/pkg/store/storepb/rpc.proto#L15)and expose `/api/v1/read` The problem is that remote read has massive limitation - it does not stream. 

We started the work to make Prometheus remote read a streaming bit, but not finished yet ): (https://github.com/improbable-eng/thanos/issues/488)

**Comment by accent-atul** [comment]
Got it. That should work. We can build proxy layer.

**Comment by bwplotka** [comment]
Awesome. If you can make it public in separate repo, that would be helpful for others as well (:

**Comment by accent-atul** [comment]
Agree, will contribute it back to the community :)
