### ISSUE TITLE
Thanos does not respect honor_labels flag

### ISSUE THREAD

**Issue by taharah** [improbable-eng/thanos#1136]
**Thanos Docker image:** improbable/thanos:v0.4.0**
**Prometheus version:** 2.9.2

**What happened**

When using the Thanos Query service I noticed that the labels were different than when directly searching via Prometheus. From what I can tell, the Thanos sidecar service is not respecting when the flag "honor_labels" is set to true. Labels when viewed via the Query service are the overwritten values. 

**What you expected to happen**

I expected the Thanos Query service to display timeseries with the same labels as those viewed directly via Prometheus.

**How to reproduce it (as minimally and precisely as possible)**:

* Create a scrape job with the flag "honor_labels" set to true
* Create a relabel rule that would override one of the labels
* View the timeseries labels in Prometheus and the Thanos Query service

**Full logs to relevant components**

N/A

**Anything else we need to know**

I noticed this when using the `kube-state-metrics` exporter on versions 0.3.2 and 0.4.0 of Thanos.

**Comment by bwplotka** [comment]
Thanks for reporting. This is expected in current form and respecting scrape honor_label is tricky, but let's discuss it and split this problem a bit. 

* Prometheus attaches some labels: 
>  ("job" and "instance" labels, manually configured target
# labels, and labels generated by service discovery implementations).
* `honor_labels` controls how to deal with conflicts if app reuse some of those labels

Sidecar repects whatever is in Prometheus, however due to remote read API not giving external labels, it attaches them without any honor logic. Just override if there is clash. Sidecar uses external labels ot advertise itself so Querier can filter out things early.

Should sidecar has honor_label like logic in case of label clash? Maybe, but I would be worried of very inconsistent query results vs what was matching against. Imagine someone querying for `metric="A"`` and Prometheus external label is `cluster="A"`, so query goes there. Prometheus returns metric with `cluster="B"` because there was clash and label was honoured. Now you do second query with `cluster="B"` filter, but well.. Querier filters out by external labels so no result. Is this what we want? (same applies to store gareway). (: 

Can we go by exact use case? What exactly label is different? What query? Just curious on use case for reusing labels. Maybe the solution is to never reuse?

**Comment by taharah** [comment]
@bwplotka your comment was very helpful. I was setting an external_label that was overriding another, and thus, this was the root cause of the issue I was seeing. It is helpful to know that this is the intended design going forward and to be extremely careful when setting external_labels to ensure no conflicts exist. 

Thank you!
