### ISSUE TITLE
Store: Hundreds of errors in logs

### ISSUE THREAD

**Issue by R4scal** [improbable-eng/thanos#1257]
Hi

I have hundreds of error in logs of store daemon, like:
<details>Logs
<p>

```
{"cacheType":"Postings","caller":"cache.go:254","curSize":8587457979,"itemSize":4253828,"iterations":500,"level":"error","maxItemSizeBytes":4294967296,"maxSizeBytes":8589934592,"msg":"After max sane iterations of LRU evictions, we still cannot allocate the item. Ignoring.","ts":"2019-06-17T07:07:37.983393384Z"}
```
</p>
</details>

I think this is not real problem. Maybe change log level to warning?

```
./thanos --version
thanos, version 0.5.0 (branch: HEAD, revision: 72820b3f41794140403fd04d6da82299f2c16447)
  build user:       root@7d72e9360b09
  build date:       20190606-10:49:10
  go version:       go1.12.5
```

**Comment by bwplotka** [comment]
Thanks for report!

So it is an error that we recover from, but it sugest really high preassure on posting index cache in store gateway. It's an error as in this case your cache is literally not working as nothing can be removed from it. 

Are you sure this is with store gateway on 0.5.0?

If that's true then https://github.com/improbable-eng/thanos/pull/1142 might be still not enough as a fix.

cc @GiedriusS

**Comment by R4scal** [comment]
Yes, store 0.5.0. I can try increase `index-cache-size` from 8g to 10g, but actually cache is not critical feature for us, because we use fast local s3-storage and don't have hight rps for store.

**Comment by abursavich** [comment]
@R4scal, if you have it, could you please provide a larger sample of those errors?  I'm interested to see how/if the size of the cache changes over time. Thanks!

**Comment by abursavich** [comment]
In my v0.4.0 store (still waiting on the next prometheus-operator release before moving to v0.5.0), once the cache thinks its full and starts triggering evictions it quickly starts complaining about too many iterations. It stays in this mostly-working mode until it evicts everything (and still thinks its nearly full). After this it keeps adding and evicting (small) things for days, but the hit ratio drops to near zero.

Cache overview:
![metrics](https://user-images.githubusercontent.com/1512418/59814015-973d4400-92c8-11e9-9ef3-a1059de33e1b.png)

Logs (max'd y-axis cuts off millions of errors):
![logs](https://user-images.githubusercontent.com/1512418/59811691-ec288c80-92bf-11e9-9ab4-31a245ffce72.png)

The logs switch from `After max sane iterations of LRU evictions, we still cannot allocate the item. Ignoring.` to `LRU has nothing more to evict, but we still cannot allocate the item. Ignoring.` once the true number of items in the cache falls to below `saneMaxIterations`.  If you zoom in there are still blips of "iteration" errors as the transition occurs.

Zoomed in on transition:
![transition](https://user-images.githubusercontent.com/1512418/59812798-1714df80-92c4-11e9-939d-19e5d02fb84d.png)

My hypothesis is that the `saneMaxIterations` value of 500 is too low due to the cache having a wide range of item sizes. For the same store as above:
- `Postings` average size is ~30KB (x500 = ~15MB)
- `Series` average size is ~100 bytes (x500 = ~50KB)
- The overall average size is ~4KB (x500 = ~2MB)

I have "iteration" error logs when trying to insert items ranging from ~130KB to ~13MB (most are between ~1.5MB and ~3.5MB).

Until "nothing more to evict" logs start appearing in v0.5.0 logs, I think the only issue is an overly-aggressive iteration restriction.

Average item sizes:
![item sizes](https://user-images.githubusercontent.com/1512418/59813994-8260b080-92c8-11e9-8b14-0437adb21efe.png)

**Comment by bwplotka** [comment]
That is very plausible! nice.
