### ISSUE TITLE
TLS support for cluster traffic?

### ISSUE THREAD

**Issue by ickymettle** [improbable-eng/thanos#322]
Are there any plans, or interest in adding TLS support for the cluster gRPC traffic? 

Our environment consists of a large number of geographically distributed datacenters and the absence of TLS support is a show stopper  for us as cluster traffic would have to transit in the clear across the public internet. 😿

**Comment by Bplotka** [comment]
Hello @ickymettle! (:

Nope, there is none currently and there is yet no plan to add it. The reason is the same as why Prometheus does not have any auth/encryption layer implemented for its UI, remote reads or writes. Basically, there are too many different types, usage options, configurations and use cases. We simply don't want to dictate how one want to certificate/encrypt/authorize the traffic. We believe that there are well-fitted tools just for this outside of Thanos.

>  absence of TLS support is a show stopper for us as cluster traffic would have to transit in the clear across the public internet. 

I disagree that without Thanos TLS you now have to send your requests in plain sight. There are a variety of solutions that fit here like nginx, L7 load balancers, [envoy](https://www.envoyproxy.io/), istio or [kedge](https://github.com/improbable-eng/kedge) that do the encryption/auth job better than Thanos will ever do. 

There is one option we could consider exposing, which is memberlist (gossip) [encryption](https://godoc.org/github.com/hashicorp/consul/vendor/github.com/hashicorp/memberlist#Keyring). There is no much documentation on it (or I am blind), so I would love to have some opinions on someone who have seen or desire global gossip. The thing is that I am not sure if you can achieve safe, reliable and fast global gossip with some proxy for encryption layer. Also there is no big configuration. Either you put keys/secrets or not. But I would be careful here as well.

**Comment by ickymettle** [comment]
Thanks for your feedback, and I completely understand the positioning. We currently utilize ghostunnel to provide mutually authenticated TLS sessions from our frontend grafana instances and federators to our individual promethei.

Where things get more complex in our environment is we have over 100 prometheus instances so the problem gets rather interesting when every instance needs to be able to gossip with every other instance.

Looks like there may be some envoy in our future, will be more than happy to document our adventures as we try and figure this out.

Thanks for all your work on Thanos, really appreciate it.

**Comment by kalebris** [comment]
just thought will mention it here as this is the pretty much the first google hit on encryption and thanos and was probably forgotten: https://github.com/improbable-eng/thanos/blob/master/docs/components/query.md

**Comment by balena** [comment]
@kalebris, by the way these gRPC options (--grpc-server-tls-cert and --grpc-server-tls-key) don't work correctly with regular CA -> Intermediate -> Server certificate chains. Logs don't help much, they show:

    /monitoring_thanos_1 sidecar command failed: setup gRPC server: server credentials: tls: private key does not match public key

You may argue that the certificate chain is incorrect, etc, but it is not:

    $ openssl verify -CAfile /etc/pki/thanos/ca.pem /etc/pki/thanos/chain.pem
    /etc/pki/thanos/chain.pem: OK
    $ openssl verify -CAfile /etc/pki/thanos/ca.pem -untrusted /etc/pki/thanos/chain.pem /etc/pki/thanos/cert.pem
    /etc/pki/thanos/cert.pem: OK

As well as the private key:

    $ openssl x509 -noout -modulus -in /etc/pki/thanos/cert.pem | openssl md5
    (stdin)= d96585822af2e879163c7273db91333e
    $ openssl rsa -noout -modulus -in /etc/pki/thanos/privkey.pem | openssl md5
    (stdin)= d96585822af2e879163c7273db91333e

I'm using `--grpc-server-tls-cert=/path/to/fullchain.pem` and `--grpc-server-tls-key=/path/to/privkey.pem`, where `fullchain.pem` is the result of `cat ca.pem chain.pem cert.pem` (Root CA + Intermediate CA + Server CA, in this order).

**Comment by ickymettle** [comment]
Try reversing the order of your concatenated certificates:

```
cat cert.pem chain.pem ca.pem -> fullchain.pem
```

The order should follow the chain back to root. Ie. `cert.pem` was signed by `chain.pem` which was signed by `ca.pem`.

**Comment by balena** [comment]
@ickymettle, thanks, it solved the case! It is going to be a good idea to document this somewhere as to avoid trial and error from others...
