### ISSUE TITLE
query: irate/rate gaps not masked by deduplication

### ISSUE THREAD

**Issue by treed** [improbable-eng/thanos#331]
I have a test Prometheus/Thanos deployment set up and I just had an instance where it looks like the deduplication isn't working.

Here's the query without dedup:

<img width="1158" alt="screen shot 2018-05-11 at 16 03 23" src="https://user-images.githubusercontent.com/71910/39950709-0eb3062a-5538-11e8-8526-7ecb23a518a8.png">

And here's the query with dedup:

<img width="1154" alt="screen shot 2018-05-11 at 16 03 54" src="https://user-images.githubusercontent.com/71910/39950712-1aef6e06-5538-11e8-8d06-0dade30c6ede.png">

The dedup appears to be just taking whatever replica A says, even though it leads to gaps in the graph, which isn't what I expected.

Is it perhaps that the gap is too short for dedup to do anything, or that I misunderstood how it's supposed to work? Or is there a bug here?

**Comment by treed** [comment]
Interesting, so is the penalty twice the duration of the last interruption or something else? That's useful to know although I'm not sure it applies here.

I assume by raw, you mean without irate. Unexpectedly, the raw data don't show gaps for either replica. Maybe it's passing irate through to the backend and then deduplicating on that?

I backed it out to 30 minutes of graph, with more on the left side of the interruption, and made two graphs, one with irate and one without. Here's A:

<img width="1306" alt="screen shot 2018-05-14 at 13 36 39" src="https://user-images.githubusercontent.com/71910/40022121-e477348a-577b-11e8-929e-76200cb0f6ed.png">

Here's B:

<img width="1301" alt="screen shot 2018-05-14 at 13 38 40" src="https://user-images.githubusercontent.com/71910/40022240-308c14da-577c-11e8-8131-3c375e830542.png">

And here's both with dedup:

<img width="1313" alt="screen shot 2018-05-14 at 13 39 57" src="https://user-images.githubusercontent.com/71910/40022341-839afc5e-577c-11e8-86ba-104bbc5c6973.png">

Let me know if you need more data.

My intention with Thanos was mostly being able to have uninterrupted graphs during periods where I need to restart/reconfigure Prometheus, with some kind of file-watcher that would handle sending the signal with a timed-lock in Redis to ensure that they don't restart too close to each other. Knowing how long that wait needs to be would be useful, assuming that's the issue.

**Comment by Bplotka** [comment]
> Interesting, so is the penalty twice the duration of the last interruption or something else? That's useful to know although I'm not sure it applies here.

Yea, and in addition, if the were samples from both replicas we still give penalty to the one that was "later".
```
// For the series we didn't pick, add a penalty twice as high as the delta of the last two
// samples to the next seek against it.
```

Yea it is hard to deduct what missed the sample and when, because graph render can potentially mask it.
Also `irate` is bit specific as it takes only 2 last samples from the 30s range you specified.  See this for more insights on irate https://youtu.be/67Ulrq6DxwA?t=1723 or this https://www.stroppykitten.com/technical/prometheus-grafana-statistics

What `rate` shows us?  

Anyway the correct way to see if there was any gap is to zoom to the range we are suspicious about (weird missing line for irate) and check graph. If we want to be 100% sure we can also change into `console` tab and ask for `<your metric without irate>[30s]` and we will see all the samples. (exact timestamps)

> Maybe it's passing irate through to the backend and then deduplicating on that?

Nope, this is not the case. We deduplicate raw samples always.

**Comment by deejay1** [comment]
>  If you are not on K8s, yea your solution is fair, but mhm, why not polling readiness endpoint as well?
Hmm, as far as I remember Prometheus reports readiness when it's ready for scraping, but that doesn't mean that all scrape targets are already run, in this case we could run into some gaps when the first server is down already and the other didn't start scraping data, so adding an additional delay could help (of course I could be wrong on this, as I didn't exactly investigate that case yet ;)

**Comment by Bplotka** [comment]
Very good point, was bit worried about it, but TBH I never have seen any drop sample from rollout process. Because we are doing it bit manually right now. (we have rollout script). Is there any way to do k8s rollout statefulsets like deployment? (: (since we have two replicas) @deejay1 ?


We may want to invest more time on this (: (Test rollout process hardly to find if we are reliable on that)

**Comment by treed** [comment]
I zoomed really far in and was unable to find any gaps in the raw metric. Unfortunately, I don't see a way to select the time with console view. Looks like the time/range selector is only on graph view?

I'm not on k8s, but I didn't know about the readiness endpoint but I suppose I should have expected it given how big Prometheus is in the k8s community. But, yeah, if it doesn't actually indicate backend-readiness, then the best it can reliably do is give me a minimum point. I guess I could wait for ready plus the scrape interval, although I'm unsure if asking Consul for the list of services occurs before or after readiness.

Using rate() has the same gap as irate().

**Comment by Bplotka** [comment]
> I zoomed really far in and was unable to find any gaps in the raw metric. Unfortunately, I don't see a way to select the time with console view. Looks like the time/range selector is only on graph view?

You can do it just fine on in Console (it's not well-known feature):
![image](https://user-images.githubusercontent.com/6950331/40161300-3cf14f1e-59a8-11e8-837f-d6f19fd13a8f.png)

Will ask awesome Prometheus community what these weird rate/irate gaps mean, but we would love to know first if there was or not any missed sample that maybe render mask.

**Comment by Bplotka** [comment]
Ok, we got answer pretty quickly. Thanks @juliusv! 

Basically I asked you in the beginning about `scrape interval` but totally forgot about it later (: It is quite important here, because then if you have 15s interval `irate/rate/increase` have either 2 or even sometimes 1 sample for `[30]` range that's why weird gaps (we need minimum of two). Can you try longer range?

@juliusv answer:
> bplotka: maybe I missed something, but if the underlying series show no gaps and the scrape interval is 15s, then an irate() window of 30s is simply not enough to reliably not produce gaps in the irate() output
you are not guaranteed to have at least 2 samples under a 30s window with a 15s scrape rate

Nice slides for understanding `rate`: https://docs.google.com/presentation/d/1CD3ZFsvi1xMzm2wepPLLnLMt9sX0bqxfxEgcr65mgBw/edit#slide=id.g38977d3a7b_0_200

**Comment by Bplotka** [comment]
I think that closes explains this issue, right? Let me know if it is not solved in your opinion.

**Comment by treed** [comment]
The scrape interval is 15s and using [40s] makes the gaps go away, but that doesn't explain why the gaps aren't filled in by deduplication when the other side doesn't have a gap. It's also only a problem when I have to reconfigure a Prometheus instance.

**Comment by juliusv** [comment]
@treed There is no gap in the underlying data, as your raw counter graphs show, but sometimes with a scrape interval of 30s, you might not have at least 2 points under a 15s rate window (depending on window-to-sample alignment), but that depends on the phase of the data collection, which is slightly different in the two Prometheus instances. But the underlying data is still not gappy (and that's all that matters for deduping/merging), just the irate itself becomes gappy after merging the data.

**Comment by juliusv** [comment]
Sorry, meant to say scrape interval of 15s and 30s rate window.

**Comment by treed** [comment]
Ahhhh okay. Thanks for the explanation.
