### ISSUE TITLE
Using compacted and downsampled blocks by thanos in Prometheus Locally

### ISSUE THREAD

**Issue by dmitriy-lukyanchikov** [improbable-eng/thanos#593]
Hello guys.

I interested in using compacted and downsampled blocks by thanos in Prometheus Locally.
I download compacted block by thanos to prometheus and it worked well.
But when i try to load downsampled block locally it raise  an error
```
 component="query engine" msg="error expanding series set" err="invalid encoding \"<unknown>\""
```
Does it possible to use downsampled block in Prometheus. If needed some code to be changed can you point me what can i do to use this blocks locally in prometheus after downsample by thanos?

**Comment by bwplotka** [comment]
Yea it won't work by Prometheus natively, because Prometheus does not support any downsampling. It is implemented as a separate encoding, so you would endup adding this into TSDB library:
https://github.com/improbable-eng/thanos/blob/master/pkg/compact/downsample/aggr.go and hooking this into chunk getter by encoding.

But... why? (:

**Comment by dmitriy-lukyanchikov** [comment]
it was just for testing purpose, thank you for answering i will close this one
