### ISSUE TITLE
Rule: access series directly access sidecar

### ISSUE THREAD

**Issue by eahydra** [improbable-eng/thanos#690]
**Thanos, Prometheus and Golang version used**

**What happened**
Hi guys, I have try to contact you from slack and twitter, but failed. 
I have a question:  I want setup some rule instances to aggregate data or do alert check.
But I have many different prometheus instances, if want to setup rules, I must setup different query layer. 

So  Can the rule component access data from sidecar directly?  So I can just add rule components and have only one query layer. 

**What you expected to happen**

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

**Anything else we need to know**

**Comment by jojohappy** [comment]
> But I have many different prometheus instances, if want to setup rules, I must setup different query layer.

I don't understand what you said. Did you mean that you would like to setup the rules dependent on the Prometheus replicas or you have not an unified `Query` layer to query the whole of `StoreAPI` servers? 
The `Thanos Rule` component needs to know about `QueryAPI` servers in order to evaluate recording and alerting rules, but not the `StoreAPI`. I think you should setup an unified `Query` layer to query metrics from your Prometheus instances.
