### ISSUE TITLE
How to Config time for upload block data from Prometheus to Object Storage, How to deduplicate?

### ISSUE THREAD

**Issue by thachnv92** [improbable-eng/thanos#720]
Hello,
I set up a thanos system, but I have 3 questions.

1. How to Config time for upload block data from Prometheus to Object Storage?
Now, every 2 hours, block data upload to Object Storage.
I want to change it from every 2 hours to 5 minutes or less more.

2. I have 3 server.
Server A: Save data from 00:00 -> 23:59 09 Jan 2019.
Server B: Save data from 00:00 -> 23:59 09 Jan 2019.
Store Gateway C: Get data from S3 from 00:00 01 Jan 2019 -> 23:59 09 Jan 2019.

I use Querier and query to 3 Server (A, B, C). It is OK?
And if I have a query get data from 00:00 01 Jan 2019 -> 23:59 09 Jan 2019, what store it use to respond to Querier?

3. I have 2 server.
Server A: Save data from 00:00 -> 23:59 09 Jan 2019.
Server B: Save data from 00:00 -> 23:59 09 Jan 2019.
When I use deduplication, I have a query get data from 00:00 01 Jan 2019 -> 23:59 09 Jan 2019, what store it use to respond to Querier? From Server A or Server B?

Thank you ^^

**Comment by bwplotka** [comment]
Hey,

You cannot change that as this is core [TSDB](https://github.com/prometheus/tsdb) decision. The block is  created only every 2h, so you cannot upload every 5m. 

If you want more "stateless" approach, you need something that supports `remote-write` . Thanos support for it is in progress:https://github.com/improbable-eng/thanos/blob/master/docs/proposals/approved/201812_thanos-remote-receive.md

**Comment by thachnv92** [comment]
@bwplotka 
Could you tell me how to deduplicate data in thanos?

Example:
I have 2 server.
Server A: Save data from 00:00 -> 23:59 09 Jan 2019.
Server B: Save data from 00:00 -> 23:59 09 Jan 2019.
When I use deduplication, I have a query get data from 00:00 01 Jan 2019 -> 23:59 09 Jan 2019, what store it use to respond to Querier? From Server A or Server B?

Thank you.

**Comment by bwplotka** [comment]
It uses from both A and B and deduplicate in runtime transparently. This way it fill any gaps if second replica has data for those gaps and vice versa (:

**Comment by thachnv92** [comment]
@bwplotka 
Sorry, But when both A and B have data, What data will be show?
Example:
Server A: value = 5
Server B: value = 7
=> result: value=?

**Comment by bwplotka** [comment]
There is a penalty based alghorithm which choose random one and if it has gaps it fills them with data from other replica (:

**Comment by thachnv92** [comment]
@bwplotka 
Sorry, I try to config upload block data to Object Storage but I can't do it.
`--storage.tsdb.min-block-duration=5m --storage.tsdb.max-block-duration=2h`

`thanos: error: unknown long flag '--storage.tsdb.min-block-duration'`

Please help me to do it. I want to every 5 mins, It will be upload block data to Object Storage.
Thank you.

**Comment by thachnv92** [comment]
@fabxc @bwplotka Please help me to do it

**Comment by thachnv92** [comment]
@fabxc @bwplotka Please help me to do it.
1. I want to every 5 mins, It will be upload block data to Object Storage.
2. I just manually upload those blocks to the bucket of course.

**Comment by thachnv92** [comment]
@fabxc @bwplotka Could you tell me how to manually upload those blocks to the bucket?

**Comment by marcdavoli** [comment]
> @fabxc @bwplotka Could you tell me how to manually upload those blocks to the bucket?

I'm also interested in this, we believe we have a use case for doing this:
We want to be able to swap workloads between 2 "cattle" k8s clusters that we build/destroy regularly.
We want to be able to use Thanos without losing the last 2h of data every time we tear down a cluster.
I know there is the option of using a PV for Prometheus, but since we would need to manipulate the data (backup/restore/import the data into the other cluster, etc.) it seems very clunky to do so.
We are envisioning having something like a pre-termination hook that manually uploads the last 2h of data to object storage and not have to deal with the PV stuff.

Is this possible? And if so, how can we do the upload manually or ideally have something built into Thanos to kick-off a one-time on-demand upload of TSDB blocks to object storage.

We are fairly new to Thanos so this might be a bad idea, your guidance is appreciated.
