### ISSUE TITLE
[query] Difference between direct Prom and query graph (~staleness)

### ISSUE THREAD

**Issue by Bplotka** [improbable-eng/thanos#75]
Somehow missing data points are ... represented differently?

(Removed  image because it could contain sensitive data)

**Comment by fabxc** [comment]
Mh, so they look largely the same. Do you mean the difference where Thanos shows the data flatlining across the gaps rather than actually showing no data?
That would smell like staleness handling, but that's all in imported packages – so not sure where any divergence would come from.

**Comment by fabxc** [comment]
Coming back to this, it seems that somehow the staleness samples are not being treated properly. We use the default `PromQL` engine, so that cannot be it.
Staleness samples are just regular samples with a float64 values. However, there are ~2^52 ways to represent NaN. We picked one discrete one of them to indicate staleness and normalize actually scraped NaN values to another one.

By our research, this is valid usage according to [IEEE754](https://en.wikipedia.org/wiki/IEEE_754):

"Two kinds of NaN: a quiet NaN (qNaN) and a signaling NaN (sNaN). A NaN may carry a payload that is intended for diagnostic information indicating the source of the NaN. The sign of a NaN has no meaning, but it may be predictable in some circumstances."

I wonder know whether somewhere along the way another NaN representation is substituted for our staleness samples for some reason. It would be easy to blame the transport layer, but we are actually moving around encoded chunks.

**Comment by fabxc** [comment]
@Bplotka can you check whether this is still an issue.

Did a quick check against GCS data. The metric (green line) stops but increases until the end, i.e. does not show the 5 minute flatline at the end. That generally looks correct.

<img width="1414" alt="screen shot 2017-12-19 at 15 34 03" src="https://user-images.githubusercontent.com/4948210/34161877-3a24cf7c-e4d2-11e7-9155-9d5f70ce8979.png">

**Comment by fabxc** [comment]
We haven't seen this in a while so I'd consider it resolved. We can reopen should someone encounter it again.
