### ISSUE TITLE
sidecar in docker can't get events via fsnotify

### ISSUE THREAD

**Issue by andyzasl** [improbable-eng/thanos#760]
Hi!
thanos docker container v0.2.1
we have such infrastructure:
3 containers:
prometheus, git-sync and thanos-sidecar
git-sync keep some dir in sync with git repo and we need thanos to detect new changes and reload prometheus.
At this time this don't work when shared dir is mounted from host. 
I think there might be way to check for changing checksum of rules dir/config to workaround of this problem.

**Comment by bwplotka** [comment]
Thanks for report. Can you elaborate more, in what way it does not work? 

It does not detects changes I guess? I thought the common error was permission denied on those mapped by  kubernetes configmap etc. This means different configmap configuration needs to be done (`path` specified).

So first of all. Is this kubernetes related? or you manually mount some dir from host? (: 

We already checksum the things is just to how to avoid polling to detect file changes..

**Comment by andyzasl** [comment]
Yep, It does not detects changes. 
No, this not the permission problem, since I could read file in sidecar container (with sidecar's uid)

**Comment by bwplotka** [comment]
Ok, as we cannot repro on prod, some unit test to repro it locally via go test would be super useful if you have time @andyzasl 

If not, someone else will pick it up.

**Comment by alex-laties** [comment]
The issue appears to be the lack of resolution of parent rule directories to symlinks on each walk.

I _believe_ this is due to [`filepath.Walk`](https://golang.org/pkg/path/filepath/#Walk) not handling symlinks, so if the rules directory itself is a symlink, the [`filepath.Walk` call in reloader.go](https://github.com/improbable-eng/thanos/blob/master/pkg/reloader/reloader.go#L210) will do nothing.
