### ISSUE TITLE
Multicloud Thanos Deployment - correct way to expose components

### ISSUE THREAD

**Issue by chris-vest** [improbable-eng/thanos#822]
Thanos version v0.1.0

We have an EKS cluster and a GKE cluster, with Prometheus & Thanos deployments in both. We want to add the GKE deployment to the Thanos in EKS. 

Currently we have a VPN connection between both k8s clusters in each cloud provider. What is the correct way to expose the necessary services and their underlying pods in GKE to the Thanos deployment in EKS?

**Comment by FUSAKLA** [comment]
Hi, I'd suggest upgrading the Thanos to the latest version as a first thing, but mainly
please ask questions on the [#thanos](https://join.slack.com/t/improbable-eng/shared_invite/enQtMzQ1ODcyMzQ5MjM4LWY5ZWZmNGM2ODc5MmViNmQ3ZTA3ZTY3NzQwOTBlMTkzZmIxZTIxODk0OWU3YjZhNWVlNDU3MDlkZGViZjhkMjc) slack channel rather than in the issues. I'm sure you will get your answers there, thanks!

Also provide bit more information about the setup possibly. Is even the Prometheus running in the EKS or you are just trying to communicate between Thanos components over the VPN?

**Comment by chris-vest** [comment]
I will ask there, thank you!
