### ISSUE TITLE
Sidecar grafana dashboard showing 49 years ago for last upload time

### ISSUE THREAD

**Issue by druss17** [improbable-eng/thanos#886]
This is a question.  The grafana dashboard under examples/grafana for thanos sidecar is displaying 49 years ago for Last Upload time.  Does anyone else see this same issue?  Is there a way to get this correct query for this singlestat?  

We are running version improbable/thanos:master-2019-01-07-270d81f.  

Thank you in advance.

**Comment by harshal-shah** [comment]
Hey, 
Yes I have seen this happen. Though I don't think it is a problem. It will stay like this until the first successful upload which should happen max in 2 hours. 

This happens because the pod exposing this metric has not yet done a successful upload so it does not expose the last-upload-timestamp.

Maybe thanos sidecar can query the bucket and find last upload timestamp in case the current value is null and that might help avoid this.

**Comment by GiedriusS** [comment]
Yes, it only happens before the first successful upload happens. Perhaps Sidecar shouldn't expose this at all before the first successful upload? Should be easy to do 🤔
