### ISSUE TITLE
compact: relax sorted label names check under `accept-malformed-index` flag

### ISSUE THREAD

**Issue by bwplotka** [improbable-eng/thanos#888]
Also in "relax" mode, we should produce metrics. 

Relevant discussion: https://github.com/improbable-eng/thanos/pull/848#discussion_r262085047

Acceptance Criteria:
* Add `debug.accept-malformed-index` flag.
* When this flag is true, relax the compaction index verification to not check if label names are sorted and produce metrics when this issue occurs so that it'd be known.

**Comment by GiedriusS** [comment]
Fixed an issue upstream which makes Prometheus produce invalid metrics with upper-case letters in label names: https://github.com/prometheus/prometheus/pull/5372
The `debug.accept-malformed-index` flag should make Thanos Compact ignore the fact that the invariant is not being upheld i.e. it should turn that check off mentioned in #848.

**Comment by GiedriusS** [comment]
Also, perhaps this should be called `--ignore-nonsorted-labels`.

**Comment by GiedriusS** [comment]
A hidden `--debug.accept-malformed-index` flag has been added to Thanos Compactor recently, courtesy of @jjneely. Thanks a lot! So now this has been fixed in Prometheus >2.8.0, and if users are running older Prometheus versions they can enable this (which is mentioned in the error message) to ignore this error.
